// Code generated by Slice Machine. DO NOT EDIT.
/* eslint-disable @typescript-eslint/no-empty-object-type */
// Manual additions below the generated block are preserved intentionally.

import type * as prismic from "@prismicio/client";
import type { CourseDocument } from "@/types/prismic";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type CoursePillarPageDocumentDataSlicesSlice =
  | PillarHeroSlice
  | QuickAnswerSlice
  | DifficultySectionSlice
  | ExamStructureSlice
  | StudyStrategySlice;

/**
 * Content for Course Pillar Page documents
 */
interface CoursePillarPageDocumentData {
  /**
   * Course Name field in *Course Pillar Page*
   */
  course_name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Course Pillar Page*
   */
  slices: prismic.SliceZone<CoursePillarPageDocumentDataSlicesSlice>;

  /**
   * Meta Title field in *Course Pillar Page*
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Course Pillar Page*
   */
  meta_description: prismic.KeyTextField;

  /**
   * Canonical URL field in *Course Pillar Page*
   */
  canonical_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Social Share Image (1200×628) field in *Course Pillar Page*
   */
  og_image: prismic.ImageField<never>;

  /**
   * Hide from search engines field in *Course Pillar Page*
   */
  no_index: prismic.BooleanField;
}

/**
 * Course Pillar Page document from Prismic
 *
 * - **API ID**: `course_pillar_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoursePillarPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CoursePillarPageDocumentData>,
    "course_pillar_page",
    Lang
  >;

interface FaqBlockDocumentData {}

/**
 * FAQ Block document from Prismic
 *
 * - **API ID**: `faq_block`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqBlockDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FaqBlockDocumentData>,
    "faq_block",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | CoursesGridSlice
  | NewsletterSignupSlice
  | TrustBarSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: AP Test Practice — Free AP Exam Prep
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Free AP practice questions.Study 5 minutes a day and score a 5. No signup required.
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

interface QuizQuestionDocumentData {}

/**
 * Quiz Question document from Prismic
 *
 * - **API ID**: `quiz_question`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuizQuestionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<QuizQuestionDocumentData>,
    "quiz_question",
    Lang
  >;

interface TopicBlogDocumentData {}

/**
 * Topic Blog Page document from Prismic
 *
 * - **API ID**: `topic_blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopicBlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TopicBlogDocumentData>,
    "topic_blog",
    Lang
  >;

interface UnitPageDocumentData {}

/**
 * Unit Page document from Prismic
 *
 * - **API ID**: `unit_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UnitPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<UnitPageDocumentData>,
    "unit_page",
    Lang
  >;

export type AllDocumentTypes =
  | CoursePillarPageDocument
  | CourseDocument
  | FaqBlockDocument
  | HomepageDocument
  | QuizQuestionDocument
  | TopicBlogDocument
  | UnitPageDocument;

/**
 * Item in *CoursesGrid → Default → Primary → Courses*
 */
export interface CoursesGridSliceDefaultPrimaryCoursesItem {
  /**
   * Course Name field in *CoursesGrid → Default → Primary → Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. AP Human Geography
   * - **API ID Path**: courses_grid.default.primary.courses[].course_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  course_name: prismic.KeyTextField;

  /**
   * Course Link field in *CoursesGrid → Default → Primary → Courses*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_grid.default.primary.courses[].course_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  course_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Short Description field in *CoursesGrid → Default → Primary → Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Master human geography concepts
   * - **API ID Path**: courses_grid.default.primary.courses[].course_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  course_description: prismic.KeyTextField;

  /**
   * Course Icon field in *CoursesGrid → Default → Primary → Courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_grid.default.primary.courses[].course_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  course_icon: prismic.ImageField<never>;
}

/**
 * Primary content in *CoursesGrid → Default → Primary*
 */
export interface CoursesGridSliceDefaultPrimary {
  /**
   * Section Heading field in *CoursesGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_grid.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Courses field in *CoursesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_grid.default.primary.courses[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  courses: prismic.GroupField<
    Simplify<CoursesGridSliceDefaultPrimaryCoursesItem>
  >;
}

/**
 * Default variation for CoursesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default courses grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoursesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoursesGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoursesGrid*
 */
type CoursesGridSliceVariation = CoursesGridSliceDefault;

/**
 * CoursesGrid Shared Slice
 *
 * - **API ID**: `courses_grid`
 * - **Description**: Grid of AP courses displayed on the homepage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoursesGridSlice = prismic.SharedSlice<
  "courses_grid",
  CoursesGridSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Headline field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Subheadline field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheadline: prismic.RichTextField;

  /**
   * CTA Button Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Start Studying Free
   * - **API ID Path**: hero_section.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Button Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default hero variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: Hero banner for APScore5 homepage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *NewsletterSignup → Default → Primary*
 */
export interface NewsletterSignupSliceDefaultPrimary {
  /**
   * Button Text field in *NewsletterSignup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Join Free
   * - **API ID Path**: newsletter_signup.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Description field in *NewsletterSignup → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_signup.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Heading field in *NewsletterSignup → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_signup.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Email Input Placeholder field in *NewsletterSignup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Enter your email
   * - **API ID Path**: newsletter_signup.default.primary.input_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  input_placeholder: prismic.KeyTextField;
}

/**
 * Default variation for NewsletterSignup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default newsletter signup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSignupSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsletterSignup*
 */
type NewsletterSignupSliceVariation = NewsletterSignupSliceDefault;

/**
 * NewsletterSignup Shared Slice
 *
 * - **API ID**: `newsletter_signup`
 * - **Description**: Newsletter signup section for homepage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSlice = prismic.SharedSlice<
  "newsletter_signup",
  NewsletterSignupSliceVariation
>;

/**
 * Item in *TrustBar → Default → Primary → Stats*
 */
export interface TrustBarSliceDefaultPrimaryStatsItem {
  /**
   * Label field in *TrustBar → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Students Helped
   * - **API ID Path**: trust_bar.default.primary.stats[].stat_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_label: prismic.KeyTextField;

  /**
   * Value field in *TrustBar → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 50,000+
   * - **API ID Path**: trust_bar.default.primary.stats[].stat_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_value: prismic.KeyTextField;
}

/**
 * Primary content in *TrustBar → Default → Primary*
 */
export interface TrustBarSliceDefaultPrimary {
  /**
   * Stats field in *TrustBar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_bar.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<TrustBarSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for TrustBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default trust bar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TrustBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TrustBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TrustBar*
 */
type TrustBarSliceVariation = TrustBarSliceDefault;

/**
 * TrustBar Shared Slice
 *
 * - **API ID**: `trust_bar`
 * - **Description**: Trust bar showing stats and social proof
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TrustBarSlice = prismic.SharedSlice<
  "trust_bar",
  TrustBarSliceVariation
>;

/**
 * Primary content in *PillarHero → Default → Primary*
 */
export interface PillarHeroSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  headline: prismic.RichTextField;
  subheadline: prismic.RichTextField;
  primary_cta_text: prismic.KeyTextField;
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
  secondary_cta_text: prismic.KeyTextField;
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *PillarHero → Items*
 */
export interface PillarHeroSliceDefaultItem {
  stat_number: prismic.KeyTextField;
  stat_label: prismic.KeyTextField;
  stat_caption: prismic.KeyTextField;
}

/**
 * Default variation for PillarHero Slice
 */
export type PillarHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PillarHeroSliceDefaultPrimary>,
  Simplify<PillarHeroSliceDefaultItem>
>;

/**
 * Slice variation for *PillarHero*
 */
type PillarHeroSliceVariation = PillarHeroSliceDefault;

/**
 * PillarHero Shared Slice
 *
 * - **API ID**: `pillar_hero`
 */
export type PillarHeroSlice = prismic.SharedSlice<
  "pillar_hero",
  PillarHeroSliceVariation
>;

/**
 * Primary content in *QuickAnswer → Default → Primary*
 */
export interface QuickAnswerSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  question: prismic.KeyTextField;
  direct_answer: prismic.RichTextField;
  expansion: prismic.RichTextField;
}

export type QuickAnswerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuickAnswerSliceDefaultPrimary>,
  never
>;

type QuickAnswerSliceVariation = QuickAnswerSliceDefault;

export type QuickAnswerSlice = prismic.SharedSlice<
  "quick_answer",
  QuickAnswerSliceVariation
>;

/**
 * Primary content in *DifficultySection → Default → Primary*
 */
export interface DifficultySectionSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  headline: prismic.RichTextField;
  lede: prismic.RichTextField;
  harder_title: prismic.KeyTextField;
  harder_bullets: prismic.RichTextField;
  easier_title: prismic.KeyTextField;
  easier_bullets: prismic.RichTextField;
  fit_title: prismic.KeyTextField;
  fit_body: prismic.RichTextField;
  maybe_title: prismic.KeyTextField;
  maybe_body: prismic.RichTextField;
}

export type DifficultySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DifficultySectionSliceDefaultPrimary>,
  never
>;

type DifficultySectionSliceVariation = DifficultySectionSliceDefault;

export type DifficultySectionSlice = prismic.SharedSlice<
  "difficulty_section",
  DifficultySectionSliceVariation
>;

/**
 * Primary content in *ExamStructure → Default → Primary*
 */
export interface ExamStructureSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  headline: prismic.RichTextField;
  lede: prismic.RichTextField;
  format_description: prismic.RichTextField;
  weights_heading: prismic.KeyTextField;
  score_heading: prismic.KeyTextField;
  score_description: prismic.RichTextField;
}

/**
 * Primary content in *ExamStructure → Items*
 */
export interface ExamStructureSliceDefaultItem {
  unit_label: prismic.KeyTextField;
  unit_weight: prismic.KeyTextField;
  unit_topic: prismic.KeyTextField;
  logistics_icon: prismic.KeyTextField;
  logistics_title: prismic.KeyTextField;
  logistics_value: prismic.KeyTextField;
}

export type ExamStructureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExamStructureSliceDefaultPrimary>,
  Simplify<ExamStructureSliceDefaultItem>
>;

type ExamStructureSliceVariation = ExamStructureSliceDefault;

export type ExamStructureSlice = prismic.SharedSlice<
  "exam_structure",
  ExamStructureSliceVariation
>;

/**
 * Primary content in *StudyStrategy → Default → Primary*
 */
export interface StudyStrategySliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
  headline: prismic.RichTextField;
  lede: prismic.RichTextField;
  mock_headline: prismic.RichTextField;
  mock_body: prismic.RichTextField;
  mock_features: prismic.KeyTextField;
  mock_cta_text: prismic.KeyTextField;
  mock_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *StudyStrategy → Items*
 */
export interface StudyStrategySliceDefaultItem {
  phase_label: prismic.KeyTextField;
  phase_icon: prismic.KeyTextField;
  phase_title: prismic.KeyTextField;
  phase_description: prismic.KeyTextField;
}

export type StudyStrategySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StudyStrategySliceDefaultPrimary>,
  Simplify<StudyStrategySliceDefaultItem>
>;

type StudyStrategySliceVariation = StudyStrategySliceDefault;

export type StudyStrategySlice = prismic.SharedSlice<
  "study_strategy",
  StudyStrategySliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CoursePillarPageDocument,
      CoursePillarPageDocumentData,
      CoursePillarPageDocumentDataSlicesSlice,
      CourseDocument,
      FaqBlockDocument,
      FaqBlockDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      QuizQuestionDocument,
      QuizQuestionDocumentData,
      TopicBlogDocument,
      TopicBlogDocumentData,
      UnitPageDocument,
      UnitPageDocumentData,
      AllDocumentTypes,
      CoursesGridSlice,
      CoursesGridSliceDefaultPrimaryCoursesItem,
      CoursesGridSliceDefaultPrimary,
      CoursesGridSliceVariation,
      CoursesGridSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      NewsletterSignupSlice,
      NewsletterSignupSliceDefaultPrimary,
      NewsletterSignupSliceVariation,
      NewsletterSignupSliceDefault,
      TrustBarSlice,
      TrustBarSliceDefaultPrimaryStatsItem,
      TrustBarSliceDefaultPrimary,
      TrustBarSliceVariation,
      TrustBarSliceDefault,
      PillarHeroSlice,
      PillarHeroSliceDefaultPrimary,
      PillarHeroSliceDefaultItem,
      PillarHeroSliceVariation,
      PillarHeroSliceDefault,
      QuickAnswerSlice,
      QuickAnswerSliceDefaultPrimary,
      QuickAnswerSliceVariation,
      QuickAnswerSliceDefault,
      DifficultySectionSlice,
      DifficultySectionSliceDefaultPrimary,
      DifficultySectionSliceVariation,
      DifficultySectionSliceDefault,
      ExamStructureSlice,
      ExamStructureSliceDefaultPrimary,
      ExamStructureSliceDefaultItem,
      ExamStructureSliceVariation,
      ExamStructureSliceDefault,
      StudyStrategySlice,
      StudyStrategySliceDefaultPrimary,
      StudyStrategySliceDefaultItem,
      StudyStrategySliceVariation,
      StudyStrategySliceDefault,
    };
  }
}
