// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  courses_grid: dynamic(() => import("./CoursesGrid")),
  hero_section: dynamic(() => import("./HeroSection")),
  newsletter_signup: dynamic(() => import("./NewsletterSignup")),
  trust_bar: dynamic(() => import("./TrustBar")),
};
